{"name": "Проверка создания пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127", "trace": "@pytest.fixture\n    def browser():\n>       driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n\ntests/test_ui/conftest.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py:55: in __init__\n    self.service.start()\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py:113: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.chrome.service.Service object at 0x7f255241c2c0>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127\n\n/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py:126: WebDriverException"}, "description": "\nЭтот тест проверяет:\n- Регистрацию пользователя с позитивным сценарием\n- Прохождение регистрации на данных параметров фикстуры registration_data_with_params (хранится в test_ui/conftest.py)\n- Проверка успеха прохождения регистрации \nИЛИ\n- Проверка предупреждения, что пользователь уже создан с таким email\n", "attachments": [{"name": "stdout", "source": "ce673f96-96b1-43b3-b1bb-4cc04e5cb528-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "registration_data_with_params", "value": "{'email': 'test3@mail.ru', 'name': 'User26', 'password': 'qwertyu2'}"}], "start": 1760646037201, "stop": 1760646037201, "uuid": "4388eff6-d874-4975-be3c-b75917754c55", "historyId": "cf18eed7ed2621160679c51f2fcec754", "testCaseId": "5a8cabc7c8bb112271ed7c9e913140fc", "fullName": "tests.test_ui.test_first#test_positive_registration_with_fixture_params", "labels": [{"name": "tag", "value": "ui"}, {"name": "epic", "value": "Аутентификация и авторизация"}, {"name": "as_id", "value": "TEST-123"}, {"name": "owner", "value": "QA - evgeny_gord"}, {"name": "feature", "value": "Регистрация пользователей"}, {"name": "suite", "value": "Смоук тесты"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests.test_ui"}, {"name": "host", "value": "eeb215c29917"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui.test_first"}], "links": [{"type": "tms", "url": "TC-789", "name": "https://testcase.com/TC-789"}, {"type": "issue", "url": "BUG-456", "name": "https://bugtracker.com/BUG-456"}, {"type": "link", "url": "https://jira.example.com/TEST-123", "name": "JIRA Task"}], "titlePath": ["tests", "test_ui", "test_first.py"]}